import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/**
 * Super Admin Panel — Stub for super admin features
 * TODO: Implement with proper RLS and audit logging
 */
import { Card, CardBody } from '../../components/ui/Card';
export default function SuperAdminPanel() {
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-bold text-gray-900", children: "Super Admin Panel" }), _jsx("p", { className: "text-gray-600 mt-2", children: "System administration and company management" })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsx(Card, { children: _jsxs(CardBody, { children: [_jsx("h2", { className: "text-lg font-semibold mb-4", children: "Companies" }), _jsx("div", { className: "bg-yellow-50 border border-yellow-200 text-yellow-700 px-4 py-2 rounded text-sm", children: "\uD83D\uDD27 List, suspend, activate companies" })] }) }), _jsx(Card, { children: _jsxs(CardBody, { children: [_jsx("h2", { className: "text-lg font-semibold mb-4", children: "Audit Logs" }), _jsx("div", { className: "bg-yellow-50 border border-yellow-200 text-yellow-700 px-4 py-2 rounded text-sm", children: "\uD83D\uDCCA View system audit trail" })] }) }), _jsx(Card, { children: _jsxs(CardBody, { children: [_jsx("h2", { className: "text-lg font-semibold mb-4", children: "Users" }), _jsx("div", { className: "bg-yellow-50 border border-yellow-200 text-yellow-700 px-4 py-2 rounded text-sm", children: "\uD83D\uDC65 List, edit, deactivate users" })] }) }), _jsx(Card, { children: _jsxs(CardBody, { children: [_jsx("h2", { className: "text-lg font-semibold mb-4", children: "Ownership Transfer" }), _jsx("div", { className: "bg-yellow-50 border border-yellow-200 text-yellow-700 px-4 py-2 rounded text-sm", children: "\uD83D\uDD04 Transfer company ownership" })] }) })] }), _jsx(Card, { children: _jsx(CardBody, { children: _jsx("div", { className: "bg-blue-50 border border-blue-200 text-blue-700 px-4 py-2 rounded text-sm", children: "\u26A0\uFE0F These features are stubs and require super_admin RLS verification via Edge Functions" }) }) })] }));
}
