-- Retention queue tracks soft-marked items before hard deletion
CREATE TABLE IF NOT EXISTS retention_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id UUID NOT NULL,
  item_type TEXT NOT NULL CHECK (item_type IN ('media', 'metadata')),
  ref_id TEXT NOT NULL,
  soft_marked_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  UNIQUE (item_type, ref_id)
);

-- Deletion logs provide auditable trail for soft and hard deletes
CREATE TABLE IF NOT EXISTS deletion_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id UUID NOT NULL,
  item_type TEXT NOT NULL CHECK (item_type IN ('media', 'metadata')),
  ref_id TEXT NOT NULL,
  deleted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  actor TEXT NOT NULL,
  notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_retention_queue_company ON retention_queue(company_id);
CREATE INDEX IF NOT EXISTS idx_deletion_logs_company ON deletion_logs(company_id);
