import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { Button } from '../components/ui/Button';
export default function MainLayout({ children }) {
    const { user, companyUser, logout, companies, activeCompanyId, switchCompany } = useAuth();
    const navigate = useNavigate();
    const handleLogout = async () => {
        await logout();
        navigate('/login');
    };
    const isDashboardRoute = window.location.pathname === '/dashboard';
    const isContractorRoute = window.location.pathname.startsWith('/contractor');
    const isCorporateRoute = window.location.pathname.startsWith('/corporate');
    return (_jsxs("div", { className: "min-h-screen bg-gray-50", children: [_jsx("header", { className: "bg-white shadow sticky top-0 z-40", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 py-4 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-8", children: [_jsxs(Link, { to: "/dashboard", className: "flex items-center gap-2", children: [_jsx("div", { className: "w-8 h-8 bg-orange-500 rounded-lg flex items-center justify-center text-white font-bold", children: "M" }), _jsx("h1", { className: "text-xl font-bold text-gray-900", children: "Mervo Ops" })] }), _jsxs("nav", { className: "hidden md:flex gap-6", children: [(isCorporateRoute || companyUser?.role !== 'contractor') && (_jsxs(_Fragment, { children: [_jsx(Link, { to: "/dashboard", className: `${isDashboardRoute ? 'text-orange-500 font-semibold' : 'text-gray-600 hover:text-gray-900'}`, children: "Dashboard" }), _jsx(Link, { to: "/corporate/jobs", className: `${isCorporateRoute ? 'text-orange-500 font-semibold' : 'text-gray-600 hover:text-gray-900'}`, children: "Jobs" }), _jsx(Link, { to: "/corporate/contractors", className: "text-gray-600 hover:text-gray-900", children: "Contractors" }), _jsx(Link, { to: "/corporate/settings", className: `text-gray-600 hover:text-gray-900`, children: "Settings" })] })), isContractorRoute && (_jsxs(_Fragment, { children: [_jsx(Link, { to: "/dashboard", className: "text-gray-600 hover:text-gray-900", children: "Today" }), _jsx(Link, { to: "/contractor/earnings", className: "text-gray-600 hover:text-gray-900", children: "Earnings" })] }))] })] }), _jsxs("div", { className: "flex items-center gap-4", children: [companies.length > 1 && (_jsx("select", { value: activeCompanyId || '', onChange: (e) => switchCompany(e.target.value), className: "text-sm border rounded px-2 py-1", children: companies.map(company => (_jsx("option", { value: company.id, children: company.name }, company.id))) })), _jsxs("div", { className: "text-right hidden sm:block", children: [_jsx("p", { className: "text-sm font-medium text-gray-900", children: user?.display_name || companyUser?.company_alias || 'User' }), _jsx("p", { className: "text-xs text-gray-500 capitalize", children: user?.role || 'contractor' })] }), _jsx(Button, { variant: "ghost", size: "sm", onClick: handleLogout, children: "Logout" })] })] }) }), _jsx("main", { className: "max-w-7xl mx-auto px-4 py-8", children: children }), _jsx("footer", { className: "bg-gray-900 text-gray-400 mt-16 py-8", children: _jsx("div", { className: "max-w-7xl mx-auto px-4 text-center text-sm", children: _jsx("p", { children: "\u00A9 2025 Mervo Ops. Field Operations Management." }) }) })] }));
}
